/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CasinoInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "fundCasino"
      | "getCasinoBalance"
      | "owner"
      | "playCoinFlip"
      | "playRoulette"
      | "playSlots"
      | "renounceOwnership"
      | "transferOwnership"
      | "withdrawProfits"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CasinoFunded"
      | "CoinFlipPlayed"
      | "OwnershipTransferred"
      | "ProfitsWithdrawn"
      | "RoulettePlayed"
      | "SlotsPlayed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "fundCasino",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getCasinoBalance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "playCoinFlip",
    values: [boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "playRoulette",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "playSlots", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawProfits",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "fundCasino", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getCasinoBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "playCoinFlip",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "playRoulette",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "playSlots", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawProfits",
    data: BytesLike
  ): Result;
}

export namespace CasinoFundedEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CoinFlipPlayedEvent {
  export type InputTuple = [
    player: AddressLike,
    bet: BigNumberish,
    choice: boolean,
    result: boolean,
    win: boolean,
    payout: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    bet: bigint,
    choice: boolean,
    result: boolean,
    win: boolean,
    payout: bigint
  ];
  export interface OutputObject {
    player: string;
    bet: bigint;
    choice: boolean;
    result: boolean;
    win: boolean;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfitsWithdrawnEvent {
  export type InputTuple = [owner: AddressLike, amount: BigNumberish];
  export type OutputTuple = [owner: string, amount: bigint];
  export interface OutputObject {
    owner: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoulettePlayedEvent {
  export type InputTuple = [
    player: AddressLike,
    bet: BigNumberish,
    betType: BigNumberish,
    betNumber: BigNumberish,
    resultNumber: BigNumberish,
    win: boolean,
    payout: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    bet: bigint,
    betType: bigint,
    betNumber: bigint,
    resultNumber: bigint,
    win: boolean,
    payout: bigint
  ];
  export interface OutputObject {
    player: string;
    bet: bigint;
    betType: bigint;
    betNumber: bigint;
    resultNumber: bigint;
    win: boolean;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SlotsPlayedEvent {
  export type InputTuple = [
    player: AddressLike,
    bet: BigNumberish,
    symbols: [BigNumberish, BigNumberish, BigNumberish],
    win: boolean,
    payout: BigNumberish
  ];
  export type OutputTuple = [
    player: string,
    bet: bigint,
    symbols: [bigint, bigint, bigint],
    win: boolean,
    payout: bigint
  ];
  export interface OutputObject {
    player: string;
    bet: bigint;
    symbols: [bigint, bigint, bigint];
    win: boolean;
    payout: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Casino extends BaseContract {
  connect(runner?: ContractRunner | null): Casino;
  waitForDeployment(): Promise<this>;

  interface: CasinoInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  fundCasino: TypedContractMethod<[], [void], "payable">;

  getCasinoBalance: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  playCoinFlip: TypedContractMethod<[heads: boolean], [void], "payable">;

  playRoulette: TypedContractMethod<
    [betType: BigNumberish, number: BigNumberish],
    [void],
    "payable"
  >;

  playSlots: TypedContractMethod<[], [void], "payable">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawProfits: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "fundCasino"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getCasinoBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "playCoinFlip"
  ): TypedContractMethod<[heads: boolean], [void], "payable">;
  getFunction(
    nameOrSignature: "playRoulette"
  ): TypedContractMethod<
    [betType: BigNumberish, number: BigNumberish],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "playSlots"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawProfits"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "CasinoFunded"
  ): TypedContractEvent<
    CasinoFundedEvent.InputTuple,
    CasinoFundedEvent.OutputTuple,
    CasinoFundedEvent.OutputObject
  >;
  getEvent(
    key: "CoinFlipPlayed"
  ): TypedContractEvent<
    CoinFlipPlayedEvent.InputTuple,
    CoinFlipPlayedEvent.OutputTuple,
    CoinFlipPlayedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ProfitsWithdrawn"
  ): TypedContractEvent<
    ProfitsWithdrawnEvent.InputTuple,
    ProfitsWithdrawnEvent.OutputTuple,
    ProfitsWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "RoulettePlayed"
  ): TypedContractEvent<
    RoulettePlayedEvent.InputTuple,
    RoulettePlayedEvent.OutputTuple,
    RoulettePlayedEvent.OutputObject
  >;
  getEvent(
    key: "SlotsPlayed"
  ): TypedContractEvent<
    SlotsPlayedEvent.InputTuple,
    SlotsPlayedEvent.OutputTuple,
    SlotsPlayedEvent.OutputObject
  >;

  filters: {
    "CasinoFunded(address,uint256)": TypedContractEvent<
      CasinoFundedEvent.InputTuple,
      CasinoFundedEvent.OutputTuple,
      CasinoFundedEvent.OutputObject
    >;
    CasinoFunded: TypedContractEvent<
      CasinoFundedEvent.InputTuple,
      CasinoFundedEvent.OutputTuple,
      CasinoFundedEvent.OutputObject
    >;

    "CoinFlipPlayed(address,uint256,bool,bool,bool,uint256)": TypedContractEvent<
      CoinFlipPlayedEvent.InputTuple,
      CoinFlipPlayedEvent.OutputTuple,
      CoinFlipPlayedEvent.OutputObject
    >;
    CoinFlipPlayed: TypedContractEvent<
      CoinFlipPlayedEvent.InputTuple,
      CoinFlipPlayedEvent.OutputTuple,
      CoinFlipPlayedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ProfitsWithdrawn(address,uint256)": TypedContractEvent<
      ProfitsWithdrawnEvent.InputTuple,
      ProfitsWithdrawnEvent.OutputTuple,
      ProfitsWithdrawnEvent.OutputObject
    >;
    ProfitsWithdrawn: TypedContractEvent<
      ProfitsWithdrawnEvent.InputTuple,
      ProfitsWithdrawnEvent.OutputTuple,
      ProfitsWithdrawnEvent.OutputObject
    >;

    "RoulettePlayed(address,uint256,uint8,uint8,uint8,bool,uint256)": TypedContractEvent<
      RoulettePlayedEvent.InputTuple,
      RoulettePlayedEvent.OutputTuple,
      RoulettePlayedEvent.OutputObject
    >;
    RoulettePlayed: TypedContractEvent<
      RoulettePlayedEvent.InputTuple,
      RoulettePlayedEvent.OutputTuple,
      RoulettePlayedEvent.OutputObject
    >;

    "SlotsPlayed(address,uint256,uint8[3],bool,uint256)": TypedContractEvent<
      SlotsPlayedEvent.InputTuple,
      SlotsPlayedEvent.OutputTuple,
      SlotsPlayedEvent.OutputObject
    >;
    SlotsPlayed: TypedContractEvent<
      SlotsPlayedEvent.InputTuple,
      SlotsPlayedEvent.OutputTuple,
      SlotsPlayedEvent.OutputObject
    >;
  };
}
